-- =====================================================================
-- V45: Reconciliação de schema — re-garante todas as colunas (heal de drift)
--
-- Contexto: o schema de produção dessincronizou do flyway_schema_history.
-- O Flyway reporta "up to date" (V44 aplicada), mas faltam colunas de várias
-- migrations — inclusive colunas do V1 (ex.: status_sincronizacao, device_name).
-- Causa provável: o V1 usa CREATE TABLE IF NOT EXISTS; se a tabela já existia
-- (incompleta) no 1º migrate, o V1 não a recriou, e nem todos os ADD COLUMN
-- posteriores preencheram tudo. Resultado: drift arbitrário, não detectável
-- pelo Flyway OSS (que só rastreia o histórico, não o schema real).
--
-- Esta migration é forward-only e 100% idempotente (ADD COLUMN IF NOT EXISTS):
-- re-afirma TODAS as colunas de TODAS as tabelas tb_*, com os tipos exatos do
-- schema correto (gerado por flyway:migrate V1–V44 num Postgres limpo, extraído
-- via format_type). No-op onde as colunas já existem (dev/test/local); adiciona
-- onde faltam (produção). Não-destrutiva: nunca dropa nem altera tipo.
--
-- Observação: re-afirma apenas COLUNAS. Tabelas/constraints/índices ausentes não
-- são cobertos aqui (drift menos provável) — ver auditoria pós-deploy.
-- =====================================================================

ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS summary_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS technical_interpretation_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS primary_cause character varying(50);
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS recommendation_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS tags text[];
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS execution_score integer;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS rationale_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS translation_failed boolean;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS analyzed_at timestamp with time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS nome character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS dominio character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS razao_social character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cnpj character varying(18);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS email_contato character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS telefone character varying(20);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS logradouro character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS numero character varying(10);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS complemento character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS bairro character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cidade character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS estado character varying(2);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cep character varying(9);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS logo_url character varying(500);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cor_primaria character varying(7);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cor_secundaria character varying(7);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS max_atletas integer;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS max_tecnicos integer;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS plano character varying(20);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_assinatura timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_expiracao timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS trial boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_fim_trial timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_ia_avancada boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_relatorios_customizados boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_integracao_strava boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_api_externa boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_group_id character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_realm character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_organization_id character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS nome character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS sobrenome character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS peso_kg numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS altura_cm numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_nascimento date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS sexo character varying(1);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS email character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS objetivo character varying(500);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS nivel_experiencia character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS ativo character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS ctl_time_constant integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS atl_time_constant integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_maxima integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_repouso integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_limiar integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultimo_teste_fc date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS pace_limiar numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS velocidade_limiar numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultimo_teste_pace date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS vo2max_estimado numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS distancia_maxima_longo integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS volume_semanal_max integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultima_lesao date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS historico_lesoes text;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS tem_lesao boolean;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS descricao_lesao character varying(1000);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS dia_preferido_longo character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS timezone character varying(50);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS created_by character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS updated_by character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS usuario_id uuid;
ALTER TABLE tb_dias_disponiveis ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_dias_disponiveis ADD COLUMN IF NOT EXISTS dia character varying(20);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS etapa_planejada_id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS ordem integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS tipo_etapa character varying(50);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS duracao interval;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS distancia_km numeric(10,3);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS fc_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS fc_max integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS pace_media interval;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS velocidade_media numeric(5,2);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS percepcao_esforco integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS cadencia_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS potencia_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS observacao character varying(500);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS split_index integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS treino_planejado_id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS ordem integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS tipo_etapa character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS descricao_etapa character varying(500);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS duracao_min integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS distancia_km numeric(10,3);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS fc_alvo_etapa character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS repeticoes integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS bloco_id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS bloco_repeticoes integer;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS faixa_min double precision;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS faixa_max double precision;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS status character varying(30);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS cor_hex character varying(7);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS recomendacao character varying(500);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS fase character varying(30);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS nome_pt character varying(100);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS duracao_semanas_min integer;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS duracao_semanas_max integer;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS volume_relativo_pct numeric(5,2);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS intensidade_relativa_pct numeric(5,2);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS enfoque character varying(200);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS proximo_fase character varying(30);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS plataforma character varying(50);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS external_athlete_id character varying(100);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS access_token text;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS refresh_token text;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS token_expira_em timestamp with time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS scopes character varying(500);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS ultima_sincronizacao timestamp with time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS sync_activity_count integer;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS last_sync_error character varying(500);
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS data date;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tss integer;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ramp_rate double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS fatigue_ratio double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS forma_percentual double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS treinos_realizados integer;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS volume_km numeric(6,2);
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS foi_dia_descanso boolean;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl_fim_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl_fim_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb_fim_dia double precision;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS nivel_experiencia character varying(20);
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS ctl_time_constant integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS atl_time_constant integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS ramp_rate_maxima double precision;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS volume_semanal_recomendado integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS contexto text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS status_geral character varying(50);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS recomendacao_treino text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS fase_periodizacao character varying(30);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_criacao timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_ultima_atualizacao date;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dia_preferido_longo character varying(20);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS ctl_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS atl_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS ramp_rate_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS volume_semanal_medio numeric(10,2);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS volume_planejado numeric(10,2);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tss_semanal_medio integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS treinos_por_semana_medio double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dias_consecutivos_treino integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dias_desde_ultimo_descanso integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS semanas_progressao_continua integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_sobrecarga boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_ramp_alto boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_dias_consecutivos boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_necessita_descanso boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS mensagem_alerta text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_prontidao_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_pos_carga_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS fc_limiar_estimado integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS pace_limiar_estimado numeric(5,4);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS confianca_inferencia_fc character varying(10);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS confianca_inferencia_pace character varying(10);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_inferencia_limiar date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS plano_treino_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS plano_metadados_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana integer;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana_inicio date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana_fim date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS data_inicio date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS data_fim date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_planejado_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_realizado_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_alvo_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tsb_inicio numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tsb_fim numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS status character varying(30);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS objetivo_semana character varying(500);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS versao bigint;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS review_status character varying(30);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS review_comment text;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS prova_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS contexto_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS prova_alvo_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS nome character varying(100);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS data_inicio date;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS objetivo character varying(500);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS nome_prova character varying(100);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tipo_prova character varying(20);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS data_prova date;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS prova_alvo boolean;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS distancia smallint;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tsb_ideal_prova double precision;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_objetivo time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_meta time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS pace_objetivo numeric(5,2);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS status_prova character varying(20);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS foi_realizada boolean;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_realizado time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS posicao_geral integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS posicao_categoria integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tss_prova integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS percepcao_esforco_prova integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS feedback_prova text;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS semanas_preparacao integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS inicio_preparacao date;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS athlete_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS race_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS generated_at timestamp with time zone;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS weeks_to_race_at_generation integer;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS projections_json jsonb;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS confidence character varying(10);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS is_official boolean;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS coach_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS coach_reviewed_at timestamp with time zone;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS ctl_at_generation numeric(6,2);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS tsb_at_generation numeric(6,2);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS regression_r_squared numeric(5,4);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS riegel_exponent_used numeric(6,4);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS riegel_calibrated boolean;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS training_weeks_used integer;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS model_used character varying(100);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_key character varying(100);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_version character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_category character varying(50);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS severity character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS confidence character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS payload_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS evidence_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS recommendations_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS executed_at timestamp with time zone;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS data_referencia date;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS tipo character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS status character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS confidence character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS reasoning jsonb;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tipo_recurso character varying(50);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS recurso_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS acao character varying(20);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS mensagem_erro text;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tentativas integer;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS proxima_tentativa timestamp without time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS tipo_treino character varying(30);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS nome_pt character varying(100);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS zona_fc_min numeric(3,2);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS zona_fc_max numeric(3,2);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS intensidade_padrao character varying(20);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS duracao_tipica_min integer;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS duracao_tipica_max integer;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS nota_ia text;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tipo_treino character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS dia_semana character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS data_treino date;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS duracao_min interval;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS intensidade character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS zona_alvo character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tss_planejado integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS intensidade_planejada double precision;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS observacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS percepcao_esforco_esperada integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS status_treino character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS justificativa_ia text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS url_externo character varying(500);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS status_sincronizacao character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS sincronizado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS ultima_tentativa_sincronizacao timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tentativas_sincronizacao integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS exportado_para text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS erro_sincronizacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS metadados_sincronizacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS criado_por character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS editado_pelo_coach boolean;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS versao bigint;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS adicionado_pelo_coach boolean;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tipo_treino character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS dia_semana character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS data_treino date;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS duracao_min interval;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS intensidade character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS zona_alvo character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tss_calculado integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS metodo_calculo_tss character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS velocidade_media double precision;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS pace_media interval;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS intensidade_real double precision;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS percepcao_esforco integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_maxima_treino integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_minima integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS potencia_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS cadencia_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS feedback_atleta text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS condicoes_climaticas character varying(100);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS qualidade_sono_noite_anterior integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS nivel_estresse integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS status character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS url_externo character varying(500);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS status_sincronizacao character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS sincronizado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS ultima_tentativa_sincronizacao timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tentativas_sincronizacao integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS exportado_para text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS erro_sincronizacao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS metadados_sincronizacao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS criado_por character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS observacao character varying(1000);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elapsed_time_seg integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS suffer_score integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS device_name character varying(200);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS gear_name character varying(200);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_status character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_score numeric(3,2);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_reason_code character varying(100);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciled_at timestamp with time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciled_by character varying(255);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS treino_planejado_id uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS tenant_id character varying(255);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS action_type character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_status character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_status character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_planned_id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_planned_id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS score numeric(3,2);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS reason_code character varying(100);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS reason_text text;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS actor_id character varying(255);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS occurred_at timestamp with time zone;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_planned_id_uuid uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_planned_id_uuid uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS nome character varying(200);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS sobrenome character varying(200);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS email character varying(100);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS avatar_url character varying(500);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS keycloak_id character varying(100);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS email_verificado boolean;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS role character varying(20);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ultimo_acesso timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ultima_sinc timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS nome character varying(120);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS email character varying(180);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS email_normalized character varying(180);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS telefone character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS perfil character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS qtd_atletas character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS aceite_lgpd boolean;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS origem character varying(40);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;

DO $$
BEGIN
    RAISE NOTICE '✅ V45 - Reconciliação de schema concluída (todas as colunas tb_* re-garantidas)';
END$$;
