-- =====================================================================
-- V45: Reconciliação de schema — re-garante tabelas e colunas (heal de drift)
--
-- O schema de produção dessincronizou do flyway_schema_history: o Flyway reporta
-- "up to date" (V44), mas faltam TABELAS inteiras (ex.: tb_faixa_tsb) e colunas de
-- várias migrations, inclusive do V1 (status_sincronizacao, device_name...),
-- quebrando queries com SQLGrammarException / relation does not exist -> HTTP 500.
-- Causa provável: V1 usa CREATE TABLE IF NOT EXISTS; se objetos já existiam
-- (incompletos) no 1º migrate, não foram (re)criados. O Flyway OSS não detecta
-- drift (só rastreia histórico), então migrate/repair sozinhos não resolvem.
--
-- Forward-only e 100% idempotente, em duas fases, com os tipos exatos do schema
-- correto (flyway:migrate V1–V44 num PG limpo; format_type / pg_get_expr):
--   1) CREATE TABLE IF NOT EXISTS  -> cria tabelas faltantes (completas, com PK)
--   2) ADD COLUMN IF NOT EXISTS    -> preenche colunas faltantes nas existentes
-- No-op onde já existe; nunca dropa nem altera tipo. Preserva todos os dados.
--
-- Cobre tabelas e colunas. FKs/índices/constraints não-PK não são reafirmados
-- aqui (drift menos provável) — ver auditoria pós-deploy (ddl-auto=validate).
-- =====================================================================

-- ----- Fase 1: tabelas faltantes -----
CREATE TABLE IF NOT EXISTS tb_analise_workout (id uuid NOT NULL DEFAULT gen_random_uuid(), treino_realizado_id uuid NOT NULL, tenant_id uuid NOT NULL, status character varying(20) NOT NULL DEFAULT 'PENDING'::character varying, summary_pt text, technical_interpretation_pt text, primary_cause character varying(50), recommendation_pt text, tags text[], execution_score integer, rationale_pt text, translation_failed boolean NOT NULL DEFAULT false, error_message text, created_at timestamp with time zone NOT NULL DEFAULT now(), analyzed_at timestamp with time zone, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_assessoria (id uuid NOT NULL DEFAULT gen_random_uuid(), nome character varying(200) NOT NULL, dominio character varying(100) NOT NULL, razao_social character varying(200), cnpj character varying(18), email_contato character varying(100), telefone character varying(20), logradouro character varying(200), numero character varying(10), complemento character varying(100), bairro character varying(100), cidade character varying(100), estado character varying(2), cep character varying(9), logo_url character varying(500), cor_primaria character varying(7) DEFAULT '#6366F1'::character varying, cor_secundaria character varying(7) DEFAULT '#EC4899'::character varying, max_atletas integer, max_tecnicos integer, plano character varying(20) NOT NULL DEFAULT 'BASIC'::character varying, data_assinatura timestamp without time zone, data_expiracao timestamp without time zone, trial boolean NOT NULL DEFAULT false, data_fim_trial timestamp without time zone, feature_ia_avancada boolean DEFAULT false, feature_relatorios_customizados boolean DEFAULT false, feature_integracao_strava boolean DEFAULT true, feature_api_externa boolean DEFAULT false, keycloak_group_id character varying(100), keycloak_realm character varying(100) DEFAULT 'menthoros-app'::character varying, ativo boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, keycloak_organization_id character varying(100), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_atleta (id uuid NOT NULL DEFAULT gen_random_uuid(), nome character varying(100) NOT NULL, sobrenome character varying(100), peso_kg numeric(5,2), altura_cm numeric(5,2), data_nascimento date, sexo character varying(1), email character varying(255), objetivo character varying(500), nivel_experiencia character varying(20) NOT NULL, ativo character varying(20) NOT NULL DEFAULT 'ATIVO'::character varying, embedding vector(1536), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, ctl_time_constant integer, atl_time_constant integer, fc_maxima integer, fc_repouso integer, fc_limiar integer, data_ultimo_teste_fc date, pace_limiar numeric(5,2), velocidade_limiar numeric(5,2), data_ultimo_teste_pace date, vo2max_estimado numeric(5,2), distancia_maxima_longo integer, volume_semanal_max integer, data_ultima_lesao date, historico_lesoes text, tem_lesao boolean DEFAULT false, descricao_lesao character varying(1000), dia_preferido_longo character varying(20), timezone character varying(50) DEFAULT 'America/Sao_Paulo'::character varying, created_by character varying(255) DEFAULT 'migration'::character varying, updated_by character varying(255) DEFAULT 'migration'::character varying, usuario_id uuid, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_dias_disponiveis (atleta_id uuid NOT NULL, dia character varying(20) NOT NULL, PRIMARY KEY (atleta_id, dia));
CREATE TABLE IF NOT EXISTS tb_etapa_realizada (id uuid NOT NULL DEFAULT gen_random_uuid(), treino_realizado_id uuid NOT NULL, etapa_planejada_id uuid, ordem integer NOT NULL, tipo_etapa character varying(50), descricao character varying(500), duracao interval, distancia_km numeric(10,3), fc_media integer, fc_max integer, pace_media interval, velocidade_media numeric(5,2), percepcao_esforco integer, cadencia_media integer, potencia_media integer, observacao character varying(500), split_index integer, elevacao_ganho_metros integer, elevacao_perda_metros integer, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_etapa_treino (id uuid NOT NULL DEFAULT gen_random_uuid(), treino_planejado_id uuid NOT NULL, ordem integer NOT NULL, tipo_etapa character varying(50) NOT NULL, descricao_etapa character varying(500), duracao_min integer, distancia_km numeric(10,3), fc_alvo_etapa character varying(50), repeticoes integer DEFAULT 1, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, ritmo_alvo character varying(50), bloco_id uuid, bloco_repeticoes integer, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_faixa_tsb (id uuid NOT NULL DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, faixa_min double precision NOT NULL, faixa_max double precision NOT NULL, status character varying(30) NOT NULL, cor_hex character varying(7) DEFAULT '#808080'::character varying, recomendacao character varying(500), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_fase_periodizacao (id uuid NOT NULL DEFAULT gen_random_uuid(), fase character varying(30) NOT NULL, nome_pt character varying(100) NOT NULL, descricao character varying(500), duracao_semanas_min integer DEFAULT 2, duracao_semanas_max integer DEFAULT 12, volume_relativo_pct numeric(5,2) DEFAULT 100, intensidade_relativa_pct numeric(5,2) DEFAULT 100, enfoque character varying(200), proximo_fase character varying(30), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_integracao_externa (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, plataforma character varying(50) NOT NULL, external_athlete_id character varying(100), access_token text, refresh_token text, token_expira_em timestamp with time zone, scopes character varying(500), ativo boolean NOT NULL DEFAULT true, ultima_sincronizacao timestamp with time zone, tenant_id uuid NOT NULL, criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em timestamp without time zone, sync_activity_count integer DEFAULT 0, last_sync_error character varying(500), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_metricas_diarias (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, data date NOT NULL, tss integer NOT NULL DEFAULT 0, ctl double precision NOT NULL DEFAULT 0.0, atl double precision NOT NULL DEFAULT 0.0, tsb double precision NOT NULL DEFAULT 0.0, ramp_rate double precision DEFAULT 0.0, fatigue_ratio double precision DEFAULT 0.0, forma_percentual double precision, treinos_realizados integer DEFAULT 0, volume_km numeric(6,2), foi_dia_descanso boolean DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, ctl_inicio_dia double precision, atl_inicio_dia double precision, tsb_inicio_dia double precision, ctl_fim_dia double precision, atl_fim_dia double precision, tsb_fim_dia double precision, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_nivel_experiencia_constants (id uuid NOT NULL DEFAULT gen_random_uuid(), nivel_experiencia character varying(20) NOT NULL, ctl_time_constant integer NOT NULL DEFAULT 42, atl_time_constant integer NOT NULL DEFAULT 7, ramp_rate_maxima double precision NOT NULL DEFAULT 1.5, volume_semanal_recomendado integer NOT NULL DEFAULT 50, descricao character varying(500), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_plano_metadados (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, contexto text, embedding vector(1536), status_geral character varying(50), recomendacao_treino text, fase_periodizacao character varying(30), data_criacao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, data_ultima_atualizacao date, dia_preferido_longo character varying(20), ctl_atual double precision DEFAULT 0.0, atl_atual double precision DEFAULT 0.0, tsb_atual double precision DEFAULT 0.0, ramp_rate_atual double precision DEFAULT 0.0, volume_semanal_medio numeric(10,2), volume_planejado numeric(10,2), tss_semanal_medio integer, treinos_por_semana_medio double precision, dias_consecutivos_treino integer DEFAULT 0, dias_desde_ultimo_descanso integer DEFAULT 0, semanas_progressao_continua integer DEFAULT 0, alerta_sobrecarga boolean DEFAULT false, alerta_ramp_alto boolean DEFAULT false, alerta_dias_consecutivos boolean DEFAULT false, alerta_necessita_descanso boolean DEFAULT false, mensagem_alerta text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, tsb_prontidao_atual double precision DEFAULT 0.0, tsb_pos_carga_atual double precision DEFAULT 0.0, fc_limiar_estimado integer, pace_limiar_estimado numeric(5,4), confianca_inferencia_fc character varying(10), confianca_inferencia_pace character varying(10), data_inferencia_limiar date, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_plano_semanal (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, plano_treino_id uuid, plano_metadados_id uuid NOT NULL, semana integer, semana_inicio date NOT NULL, semana_fim date NOT NULL, data_inicio date, data_fim date, volume_planejado_km numeric(10,3) NOT NULL DEFAULT 0, volume_realizado_km numeric(10,3), volume_alvo_km numeric(10,3), tsb_inicio numeric(10,3), tsb_fim numeric(10,3), status character varying(30) NOT NULL DEFAULT 'RASCUNHO'::character varying, objetivo_semana character varying(500), versao bigint DEFAULT 0, observacoes text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, review_status character varying(30) NOT NULL DEFAULT 'AGUARDANDO_REVISAO'::character varying, review_comment text, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_plano_treino (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, prova_id uuid NOT NULL, contexto_id uuid, prova_alvo_id uuid, nome character varying(100) NOT NULL, descricao text NOT NULL, data_inicio date NOT NULL, objetivo character varying(500) NOT NULL, status character varying(20) NOT NULL DEFAULT 'ATIVO'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_prova (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, nome_prova character varying(100) NOT NULL, tipo_prova character varying(20) NOT NULL, data_prova date, prova_alvo boolean DEFAULT false, distancia smallint, tsb_ideal_prova double precision, distancia_km numeric(8,2), tempo_objetivo time without time zone, tempo_meta time without time zone, pace_objetivo numeric(5,2), status_prova character varying(20) NOT NULL DEFAULT 'PLANEJADA'::character varying, foi_realizada boolean DEFAULT false, tempo_realizado time without time zone, posicao_geral integer, posicao_categoria integer, tss_prova integer, percepcao_esforco_prova integer, feedback_prova text, semanas_preparacao integer, inicio_preparacao date, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_race_projection_snapshot (id uuid NOT NULL DEFAULT gen_random_uuid(), athlete_id uuid NOT NULL, race_id uuid, tenant_id uuid NOT NULL, generated_at timestamp with time zone NOT NULL DEFAULT now(), weeks_to_race_at_generation integer, projections_json jsonb NOT NULL, confidence character varying(10) NOT NULL, is_official boolean NOT NULL DEFAULT false, coach_id uuid NOT NULL, coach_reviewed_at timestamp with time zone, ctl_at_generation numeric(6,2), tsb_at_generation numeric(6,2), regression_r_squared numeric(5,4), riegel_exponent_used numeric(6,4), riegel_calibrated boolean NOT NULL DEFAULT false, training_weeks_used integer, model_used character varying(100), PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_skill_execution (id uuid NOT NULL DEFAULT gen_random_uuid(), skill_key character varying(100) NOT NULL, skill_version character varying(20) NOT NULL, skill_category character varying(50), severity character varying(20) NOT NULL, confidence character varying(20) NOT NULL, payload_json jsonb, evidence_json jsonb, recommendations_json jsonb, tenant_id uuid NOT NULL, atleta_id uuid, plano_semanal_id uuid, treino_realizado_id uuid, executed_at timestamp with time zone NOT NULL DEFAULT now(), data_referencia date, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_sugestao_coach (id uuid NOT NULL DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, atleta_id uuid NOT NULL, tipo character varying NOT NULL, status character varying NOT NULL DEFAULT 'PENDING'::character varying, confidence character varying NOT NULL DEFAULT 'MEDIUM'::character varying, summary text NOT NULL, reasoning jsonb, created_at timestamp with time zone NOT NULL DEFAULT now(), reviewed_at timestamp with time zone, expires_at timestamp with time zone, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_sync_log (id uuid NOT NULL DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, atleta_id uuid NOT NULL, tipo_recurso character varying(50) NOT NULL, recurso_id uuid NOT NULL, acao character varying(20) NOT NULL, fonte_dados character varying(50) NOT NULL, external_id character varying(255), status character varying(20) NOT NULL, mensagem_erro text, tentativas integer DEFAULT 1, proxima_tentativa timestamp without time zone, criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_tipo_treino (id uuid NOT NULL DEFAULT gen_random_uuid(), tipo_treino character varying(30) NOT NULL, nome_pt character varying(100) NOT NULL, descricao character varying(500), zona_fc_min numeric(3,2), zona_fc_max numeric(3,2), intensidade_padrao character varying(20), duracao_tipica_min integer, duracao_tipica_max integer, nota_ia text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_treino_planejado (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, plano_semanal_id uuid NOT NULL, tipo_treino character varying(20) NOT NULL, dia_semana character varying(20) NOT NULL, data_treino date, distancia_km numeric(8,2), duracao_min interval, intensidade character varying(20), descricao text, zona_alvo character varying(50), ritmo_alvo character varying(50), elevacao_ganho_metros integer, elevacao_perda_metros integer, tss_planejado integer, intensidade_planejada double precision, observacao text, percepcao_esforco_esperada integer, status_treino character varying(50), justificativa_ia text, fonte_dados character varying(50), url_externo character varying(500), status_sincronizacao character varying(50), sincronizado_em timestamp without time zone, ultima_tentativa_sincronizacao timestamp without time zone, tentativas_sincronizacao integer DEFAULT 0, exportado_para text, erro_sincronizacao text, metadados_sincronizacao text, external_id character varying(255), criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em timestamp without time zone, criado_por character varying(50), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, editado_pelo_coach boolean NOT NULL DEFAULT false, versao bigint NOT NULL DEFAULT 0, adicionado_pelo_coach boolean NOT NULL DEFAULT false, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_treino_realizado (id uuid NOT NULL DEFAULT gen_random_uuid(), atleta_id uuid NOT NULL, tipo_treino character varying(20) NOT NULL, dia_semana character varying(20) NOT NULL, data_treino date, distancia_km numeric(8,2), duracao_min interval, intensidade character varying(20), descricao text, zona_alvo character varying(50), ritmo_alvo character varying(50), elevacao_ganho_metros integer, elevacao_perda_metros integer, tss_calculado integer, metodo_calculo_tss character varying(50), velocidade_media double precision, pace_media interval, intensidade_real double precision, percepcao_esforco integer, fc_media integer, fc_maxima_treino integer, fc_minima integer, potencia_media integer, cadencia_media integer, feedback_atleta text, condicoes_climaticas character varying(100), qualidade_sono_noite_anterior integer, nivel_estresse integer, status character varying(50), fonte_dados character varying(50), url_externo character varying(500), status_sincronizacao character varying(50), sincronizado_em timestamp without time zone, ultima_tentativa_sincronizacao timestamp without time zone, tentativas_sincronizacao integer DEFAULT 0, exportado_para text, erro_sincronizacao text, metadados_sincronizacao text, external_id character varying(255), plano_semanal_id uuid, criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em timestamp without time zone, criado_por character varying(50), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tenant_id uuid NOT NULL, observacao character varying(1000), elapsed_time_seg integer, suffer_score integer, device_name character varying(200), gear_name character varying(200), reconciliation_status character varying(50), reconciliation_score numeric(3,2), reconciliation_reason_code character varying(100), reconciled_at timestamp with time zone, reconciled_by character varying(255), treino_planejado_id uuid, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_treino_reconciliacao (id bigint NOT NULL DEFAULT nextval('tb_treino_reconciliacao_id_seq'::regclass), tenant_id character varying(255) NOT NULL, treino_realizado_id uuid NOT NULL, action_type character varying(50) NOT NULL, before_status character varying(50), after_status character varying(50), before_planned_id bigint, after_planned_id bigint, score numeric(3,2), reason_code character varying(100), reason_text text, actor_id character varying(255) NOT NULL, occurred_at timestamp with time zone NOT NULL DEFAULT now(), before_planned_id_uuid uuid, after_planned_id_uuid uuid, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_usuario (id uuid NOT NULL DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome character varying(200) NOT NULL, sobrenome character varying(200), email character varying(100) NOT NULL, avatar_url character varying(500), keycloak_id character varying(100), email_verificado boolean DEFAULT false, role character varying(20) NOT NULL DEFAULT 'TECNICO'::character varying, ativo boolean NOT NULL DEFAULT true, ultimo_acesso timestamp without time zone, ultima_sinc timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS tb_waitlist (id uuid NOT NULL DEFAULT gen_random_uuid(), nome character varying(120) NOT NULL, email character varying(180) NOT NULL, email_normalized character varying(180) NOT NULL, telefone character varying(20), perfil character varying(20) NOT NULL, qtd_atletas character varying(20), aceite_lgpd boolean NOT NULL DEFAULT false, origem character varying(40) DEFAULT 'landing'::character varying, created_at timestamp with time zone NOT NULL DEFAULT now(), PRIMARY KEY (id));

-- ----- Fase 2: colunas faltantes -----
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS summary_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS technical_interpretation_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS primary_cause character varying(50);
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS recommendation_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS tags text[];
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS execution_score integer;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS rationale_pt text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS translation_failed boolean;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE tb_analise_workout ADD COLUMN IF NOT EXISTS analyzed_at timestamp with time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS nome character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS dominio character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS razao_social character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cnpj character varying(18);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS email_contato character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS telefone character varying(20);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS logradouro character varying(200);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS numero character varying(10);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS complemento character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS bairro character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cidade character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS estado character varying(2);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cep character varying(9);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS logo_url character varying(500);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cor_primaria character varying(7);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS cor_secundaria character varying(7);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS max_atletas integer;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS max_tecnicos integer;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS plano character varying(20);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_assinatura timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_expiracao timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS trial boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS data_fim_trial timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_ia_avancada boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_relatorios_customizados boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_integracao_strava boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS feature_api_externa boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_group_id character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_realm character varying(100);
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_assessoria ADD COLUMN IF NOT EXISTS keycloak_organization_id character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS nome character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS sobrenome character varying(100);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS peso_kg numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS altura_cm numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_nascimento date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS sexo character varying(1);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS email character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS objetivo character varying(500);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS nivel_experiencia character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS ativo character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS ctl_time_constant integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS atl_time_constant integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_maxima integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_repouso integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS fc_limiar integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultimo_teste_fc date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS pace_limiar numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS velocidade_limiar numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultimo_teste_pace date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS vo2max_estimado numeric(5,2);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS distancia_maxima_longo integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS volume_semanal_max integer;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS data_ultima_lesao date;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS historico_lesoes text;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS tem_lesao boolean;
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS descricao_lesao character varying(1000);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS dia_preferido_longo character varying(20);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS timezone character varying(50);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS created_by character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS updated_by character varying(255);
ALTER TABLE tb_atleta ADD COLUMN IF NOT EXISTS usuario_id uuid;
ALTER TABLE tb_dias_disponiveis ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_dias_disponiveis ADD COLUMN IF NOT EXISTS dia character varying(20);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS etapa_planejada_id uuid;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS ordem integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS tipo_etapa character varying(50);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS duracao interval;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS distancia_km numeric(10,3);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS fc_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS fc_max integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS pace_media interval;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS velocidade_media numeric(5,2);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS percepcao_esforco integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS cadencia_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS potencia_media integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS observacao character varying(500);
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS split_index integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_etapa_realizada ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS treino_planejado_id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS ordem integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS tipo_etapa character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS descricao_etapa character varying(500);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS duracao_min integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS distancia_km numeric(10,3);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS fc_alvo_etapa character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS repeticoes integer;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS bloco_id uuid;
ALTER TABLE tb_etapa_treino ADD COLUMN IF NOT EXISTS bloco_repeticoes integer;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS faixa_min double precision;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS faixa_max double precision;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS status character varying(30);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS cor_hex character varying(7);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS recomendacao character varying(500);
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_faixa_tsb ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS fase character varying(30);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS nome_pt character varying(100);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS duracao_semanas_min integer;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS duracao_semanas_max integer;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS volume_relativo_pct numeric(5,2);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS intensidade_relativa_pct numeric(5,2);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS enfoque character varying(200);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS proximo_fase character varying(30);
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_fase_periodizacao ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS plataforma character varying(50);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS external_athlete_id character varying(100);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS access_token text;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS refresh_token text;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS token_expira_em timestamp with time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS scopes character varying(500);
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS ultima_sincronizacao timestamp with time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS sync_activity_count integer;
ALTER TABLE tb_integracao_externa ADD COLUMN IF NOT EXISTS last_sync_error character varying(500);
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS data date;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tss integer;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ramp_rate double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS fatigue_ratio double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS forma_percentual double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS treinos_realizados integer;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS volume_km numeric(6,2);
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS foi_dia_descanso boolean;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb_inicio_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS ctl_fim_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS atl_fim_dia double precision;
ALTER TABLE tb_metricas_diarias ADD COLUMN IF NOT EXISTS tsb_fim_dia double precision;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS nivel_experiencia character varying(20);
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS ctl_time_constant integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS atl_time_constant integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS ramp_rate_maxima double precision;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS volume_semanal_recomendado integer;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_nivel_experiencia_constants ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS contexto text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS embedding vector(1536);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS status_geral character varying(50);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS recomendacao_treino text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS fase_periodizacao character varying(30);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_criacao timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_ultima_atualizacao date;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dia_preferido_longo character varying(20);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS ctl_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS atl_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS ramp_rate_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS volume_semanal_medio numeric(10,2);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS volume_planejado numeric(10,2);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tss_semanal_medio integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS treinos_por_semana_medio double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dias_consecutivos_treino integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS dias_desde_ultimo_descanso integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS semanas_progressao_continua integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_sobrecarga boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_ramp_alto boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_dias_consecutivos boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS alerta_necessita_descanso boolean;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS mensagem_alerta text;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_prontidao_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS tsb_pos_carga_atual double precision;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS fc_limiar_estimado integer;
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS pace_limiar_estimado numeric(5,4);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS confianca_inferencia_fc character varying(10);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS confianca_inferencia_pace character varying(10);
ALTER TABLE tb_plano_metadados ADD COLUMN IF NOT EXISTS data_inferencia_limiar date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS plano_treino_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS plano_metadados_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana integer;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana_inicio date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS semana_fim date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS data_inicio date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS data_fim date;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_planejado_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_realizado_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS volume_alvo_km numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tsb_inicio numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tsb_fim numeric(10,3);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS status character varying(30);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS objetivo_semana character varying(500);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS versao bigint;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS observacoes text;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS review_status character varying(30);
ALTER TABLE tb_plano_semanal ADD COLUMN IF NOT EXISTS review_comment text;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS prova_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS contexto_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS prova_alvo_id uuid;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS nome character varying(100);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS data_inicio date;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS objetivo character varying(500);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_plano_treino ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS nome_prova character varying(100);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tipo_prova character varying(20);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS data_prova date;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS prova_alvo boolean;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS distancia smallint;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tsb_ideal_prova double precision;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_objetivo time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_meta time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS pace_objetivo numeric(5,2);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS status_prova character varying(20);
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS foi_realizada boolean;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tempo_realizado time without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS posicao_geral integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS posicao_categoria integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tss_prova integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS percepcao_esforco_prova integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS feedback_prova text;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS semanas_preparacao integer;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS inicio_preparacao date;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_prova ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS athlete_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS race_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS generated_at timestamp with time zone;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS weeks_to_race_at_generation integer;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS projections_json jsonb;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS confidence character varying(10);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS is_official boolean;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS coach_id uuid;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS coach_reviewed_at timestamp with time zone;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS ctl_at_generation numeric(6,2);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS tsb_at_generation numeric(6,2);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS regression_r_squared numeric(5,4);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS riegel_exponent_used numeric(6,4);
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS riegel_calibrated boolean;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS training_weeks_used integer;
ALTER TABLE tb_race_projection_snapshot ADD COLUMN IF NOT EXISTS model_used character varying(100);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_key character varying(100);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_version character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS skill_category character varying(50);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS severity character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS confidence character varying(20);
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS payload_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS evidence_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS recommendations_json jsonb;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS executed_at timestamp with time zone;
ALTER TABLE tb_skill_execution ADD COLUMN IF NOT EXISTS data_referencia date;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS tipo character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS status character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS confidence character varying;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS reasoning jsonb;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone;
ALTER TABLE tb_sugestao_coach ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tipo_recurso character varying(50);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS recurso_id uuid;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS acao character varying(20);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS mensagem_erro text;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS tentativas integer;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS proxima_tentativa timestamp without time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_sync_log ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS tipo_treino character varying(30);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS nome_pt character varying(100);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS descricao character varying(500);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS zona_fc_min numeric(3,2);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS zona_fc_max numeric(3,2);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS intensidade_padrao character varying(20);
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS duracao_tipica_min integer;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS duracao_tipica_max integer;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS nota_ia text;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_tipo_treino ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tipo_treino character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS dia_semana character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS data_treino date;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS duracao_min interval;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS intensidade character varying(20);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS zona_alvo character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tss_planejado integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS intensidade_planejada double precision;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS observacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS percepcao_esforco_esperada integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS status_treino character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS justificativa_ia text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS url_externo character varying(500);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS status_sincronizacao character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS sincronizado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS ultima_tentativa_sincronizacao timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tentativas_sincronizacao integer;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS exportado_para text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS erro_sincronizacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS metadados_sincronizacao text;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS criado_por character varying(50);
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS editado_pelo_coach boolean;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS versao bigint;
ALTER TABLE tb_treino_planejado ADD COLUMN IF NOT EXISTS adicionado_pelo_coach boolean;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS atleta_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tipo_treino character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS dia_semana character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS data_treino date;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS distancia_km numeric(8,2);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS duracao_min interval;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS intensidade character varying(20);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS descricao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS zona_alvo character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS ritmo_alvo character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elevacao_ganho_metros integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elevacao_perda_metros integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tss_calculado integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS metodo_calculo_tss character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS velocidade_media double precision;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS pace_media interval;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS intensidade_real double precision;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS percepcao_esforco integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_maxima_treino integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fc_minima integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS potencia_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS cadencia_media integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS feedback_atleta text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS condicoes_climaticas character varying(100);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS qualidade_sono_noite_anterior integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS nivel_estresse integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS status character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS fonte_dados character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS url_externo character varying(500);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS status_sincronizacao character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS sincronizado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS ultima_tentativa_sincronizacao timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tentativas_sincronizacao integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS exportado_para text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS erro_sincronizacao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS metadados_sincronizacao text;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS plano_semanal_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS criado_por character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS observacao character varying(1000);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS elapsed_time_seg integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS suffer_score integer;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS device_name character varying(200);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS gear_name character varying(200);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_status character varying(50);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_score numeric(3,2);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciliation_reason_code character varying(100);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciled_at timestamp with time zone;
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS reconciled_by character varying(255);
ALTER TABLE tb_treino_realizado ADD COLUMN IF NOT EXISTS treino_planejado_id uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS tenant_id character varying(255);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS treino_realizado_id uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS action_type character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_status character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_status character varying(50);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_planned_id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_planned_id bigint;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS score numeric(3,2);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS reason_code character varying(100);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS reason_text text;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS actor_id character varying(255);
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS occurred_at timestamp with time zone;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS before_planned_id_uuid uuid;
ALTER TABLE tb_treino_reconciliacao ADD COLUMN IF NOT EXISTS after_planned_id_uuid uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS tenant_id uuid;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS nome character varying(200);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS sobrenome character varying(200);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS email character varying(100);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS avatar_url character varying(500);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS keycloak_id character varying(100);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS email_verificado boolean;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS role character varying(20);
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ativo boolean;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ultimo_acesso timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS ultima_sinc timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE tb_usuario ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS nome character varying(120);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS email character varying(180);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS email_normalized character varying(180);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS telefone character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS perfil character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS qtd_atletas character varying(20);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS aceite_lgpd boolean;
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS origem character varying(40);
ALTER TABLE tb_waitlist ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;

DO $$
BEGIN
    RAISE NOTICE '✅ V45 - Reconciliação de schema concluída (tabelas + colunas tb_* re-garantidas)';
END$$;
